on:
  pull_request:
    paths:
      - 'robo-plater/**'
  push:
    branches:
      - main
    paths:
      - 'robo-plater/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: cd robo-plater

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
